---
- name: Install ufw
  ansible.builtin.apt:
    name:
      - ufw

- name: Enable ufw
  ansible.builtin.ufw:
    state: enabled

- name: Allow WireGuard
  ansible.builtin.ufw:
    rule: allow
    port: "51820"
    proto: udp