---
- name: Update packages
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes

- name: Import Firewall tasks
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall

- name: Import Wireguard tasks
  ansible.builtin.import_tasks: wireguard.yml
  tags: wireguard

- name: Import Wireguard UI tasks
  ansible.builtin.import_tasks: wireguard-ui.yml
  tags: wireguard-ui