---
- name: apt-get update
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes

- import_tasks: firewall.yml
  tags: firewall

- import_tasks: wireguard.yml
  tags: wireguard

- import_tasks: wireguard-ui.yml
  tags: wireguard-ui