---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-wireguard"
      include_role:
        name: "ansible-wireguard"
      tags:
        - always
  vars:
    peers:
      - name: server1
        public_key: 6SeYZu1fy/yoG4EDZwCZ9yZbEMKBL0un3EzcyOYCQAw=
      - name: server2
        public_key: C2pw84c7zwaTuoQbuYiGjCBHIKtedRMB1EYc+GkhTis=
        allowed_ips: 10.0.0.0/24
