---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-wireguard"
      ansible.builtin.include_role:
        name: "ansible-wireguard"
      tags:
        - always
  vars:
    wireguard_ui:
      password: abc123
